# Generated by Django 5.1.dev20240419123637 on 2024-10-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="reactivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("categoria", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("g", "Gramos"),
                            ("mg", "Miligramos"),
                            ("ml", "Mililitros"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
