# Generated by Django 5.1.dev20240419123637 on 2024-12-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="reactivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("cantidad_total", models.PositiveIntegerField()),
                (
                    "cantidad_por_unidad",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("g", "Gramos"),
                            ("mg", "Miligramos"),
                            ("uL", "Microlitros"),
                            ("mL", "Mililitros"),
                            ("L", "Litros"),
                        ],
                        default="g",
                        max_length=100,
                    ),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Adquisición"
                    ),
                ),
                (
                    "condiciones_almacenamiento",
                    models.CharField(
                        choices=[
                            ("ambiente", "Temperatura ambiente"),
                            ("refrigerador_4", "Refrigerador (4°C)"),
                            ("congelador_20", "Congelador (-20°C)"),
                            ("congelador_80", "Congelador (-80°C)"),
                        ],
                        default="ambiente",
                        max_length=20,
                        verbose_name="Condiciones de Almacenamiento",
                    ),
                ),
            ],
        ),
    ]
