# Generated by Django 5.1.dev20240419123637 on 2024-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactivo",
            name="cantidad_por_unidad",
            field=models.FloatField(),
        ),
    ]
