# Generated by Django 5.1.dev20240419123637 on 2024-12-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consola", "0004_experimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimento",
            name="Reactivo",
        ),
        migrations.RemoveField(
            model_name="experimento",
            name="cantidad_usada",
        ),
        migrations.CreateModel(
            name="ReactivoUsado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_usada", models.FloatField()),
                (
                    "experimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consola.experimento",
                    ),
                ),
                (
                    "reactivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consola.reactivo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experimento",
            name="reactivos",
            field=models.ManyToManyField(
                through="consola.ReactivoUsado",
                to="consola.reactivo",
                verbose_name="Reactivos para experimentos",
            ),
        ),
    ]
