# Generated by Django 5.1.dev20240419123637 on 2024-12-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consola", "0005_remove_experimento_reactivo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experimento",
            old_name="date",
            new_name="fecha",
        ),
    ]
